name: Build binary and docker image

on:
  push:
    tags:
      - v*
  workflow_dispatch:

env:
  APP_NAME: ilogtail
  DOCKERHUB_REPO: registry.cn-hangzhou.aliyuncs.com/kindlingx/ilogtail

jobs:
  main:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.21
      
      - name: Generate App Version
        run: |
          TAG=$(git describe --tags --exact-match 2>/dev/null || echo "")
          if [ -n "$TAG" ]; then
            echo "APP_VERSION=$TAG" >> $GITHUB_ENV
          else
            BRANCH=$(git rev-parse --abbrev-ref HEAD)
            COMMIT=$(git rev-parse --short HEAD)
            echo "APP_VERSION=${BRANCH}-${COMMIT}" >> $GITHUB_ENV
          fi

      
      - name: Build binary
        run: |
          VERSION=${{ env.APP_VERSION }} make dist
      
      - name: Upload to OSS
        env:
          OSS_ACCESS_KEY_ID: ${{ secrets.OSS_ACCESS_KEY_ID }}
          OSS_ACCESS_KEY_SECRET: ${{ secrets.OSS_ACCESS_KEY_SECRET }}
          OSS_BUCKET: apo-oss
          OSS_ENDPOINT: https://oss-cn-hangzhou.aliyuncs.com/
        run: |
          curl https://gosspublic.alicdn.com/ossutil/install.sh | sudo bash
          sudo ossutil config -e $OSS_ENDPOINT -i $OSS_ACCESS_KEY_ID -k $OSS_ACCESS_KEY_SECRET -L CH -c /root/.ossutilconfig
          sudo ossutil cp ilogtail-${{ env.APP_VERSION }}.linux-amd64.tar.gz oss://$OSS_BUCKET/ilogtail-${{ env.APP_VERSION }}.linux-amd64.tar.gz

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          registry: registry.cn-hangzhou.aliyuncs.com
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build docker image and push
        run: |
          VERSION=${{ env.APP_VERSION }} DOCKER_REPOSITORY=${{ env.DOCKERHUB_REPO }} make docker
          docker push ${{ env.DOCKERHUB_REPO }}:${{ env.APP_VERSION }}

